export enum PrintServerEnum {
  UNQUALIFIED_PLASMA_TRANSFER = 'UNQUALIFIED_PLASMA_TRANSFER',
  DESTROYED_UNQUALIFIED_PLASMA = 'DESTROYED_UNQUALIFIED_PLASMA',
  UNQUALIFIED_RAW_PLASMA = 'UNQUALIFIED_RAW_PLASMA',
  NON_PLASMA_TRANSFER_RECORD = 'NON_PLASMA_TRANSFER_RECORD',
  RAW_PLASMA_TRANSFER = 'RAW_PLASMA_TRANSFER',
}
